INSERT INTO product (name, description, price) VALUES ('iPhone 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 3590.5);
INSERT INTO product (name, description, price) VALUES ('Smart TV', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2190.0);
INSERT INTO product (name, description, price) VALUES ('Macbook Pro', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1250.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1200.0);
INSERT INTO product (name, description, price) VALUES ('Rails for Dummies', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 100.99);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Ex', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer X', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Alfa', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1850.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Tera', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1950.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Y', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1700.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Nitro', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1450.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Card', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1850.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Plus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Hera', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2250.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Weed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2200.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Max',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2340.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Turbo', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1280.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Hot', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1450.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Ez', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1750.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Tr', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1650.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Tx', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1680.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Er', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1850.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Min', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2250.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Boo', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 2350.0);
INSERT INTO product (name, description, price) VALUES ('PC Gamer Foo', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 4170.0);

